### ISSUE TITLE
코드리뷰 받고싶습니다....

### ISSUE THREAD

**Issue by godjooyoung** [godjooyoung/first-react-to-do#2]
기술 매니저님.. 제 초라한 코드...리뷰,,부탁드립니다.. 뭐가 부족한지...보면서 이건 왜 이렇게 짠건지 의문 드는 이상한 것들 있으면 꼭 말씀주세요!!
과제내용 첨부합니다.
- UI 구현하기
- Todo 추가 하기
- Todo 삭제 하기
- Todo 완료 상태 변경하기
제목과 내용을 입력하고, [추가하기] 버튼을 클릭하면 Working에 새로운 Todo가 추가되고 제목 input과 내용 input은 다시 빈 값으로 바뀌도록 구성해주세요.
Todo의 isDone 상태가 true이면, 상태 버튼의 라벨을 취소, isDone이 false 이면 라벨을 완료 로 조건부 렌더링 해주세요.
Todo의 상태가 Working 이면 위쪽에 위치하고, Done이면 아래쪽에 위치하도록 구현합니다.
Layout의 최대 넓이는 1200px, 최소 넓이는 800px로 제한하고, 전체 화면의 가운데로 정렬해주세요.
- todo의 initial state는 `{id: 0, title: “”, body: “”, isDone: false}` 입니다.

**Comment by skdud4659** [comment]
안녕하세요, 코드 리뷰를 진행하게 된 김나영입니다:)

개발에는 정답이란 없고 조금 더 제가 보았을 때 나은 방향으로 가시길 바라는 마음으로 코멘트 남기는 부분이니 참고 부탁드립니다.

1. **README**
작은 프로젝트라도 레포 README정리해보시는 부분 좋습니다.
REAME는 사소한 부분이지만 해당 레포를 가장 잘 설명할 수 있는 부분이고, 사실 레포 이름만으로는 서비스에 대한 내용을 알기엔 부족함이 있어 프로젝트에 관한 레포라면 기재해 주는 것이 좋습니다.
내용은 비교적 자유로우나 기능뿐만 아니라 진행하며 어려웠던 점, 러닝 포인트 등의 내용이 들어가도 좋습니다.

2. **불필요한 파일 삭제**
CRA로 프로젝트를 만들면 초기에 생성되는 React 페이지가 있습니다.
해당 페이지를 구성하기 위한 로고, css, js 파일 등이 있는데 우린 그 초기 페이지가 아닌 우리만의 페이지로 바꾸어 사용하기 때문에 해당 파일들은 필요가 없어지거나 다른 역할로 바꾸어 사용하게 됩니다.
(현재 프로젝트는 간략하기 때문에 App.css, App.js에서 구현하신 것 같은데 조금 더 사이즈가 있는 프로젝트를 진행할 때 참고하시면 좋을 것 같습니다.)
그 외에도 불필요하게 생성되는 파일들이 있는데 우리 프로젝트에서 사용되지 않는 파일은 삭제하여 파일링을 조금 더 깔끔하게 관리하는 습관을 기르는 것이 좋습니다.
필요없는 파일은 하나씩 삭제해가며 스스로 찾아보세요.

3. **동일한 코드의 반복 최소화**
버튼이나 인풋 등에서 동일한 이벤트에서 적용되는 여러개의 함수들이 생기죠.
이런 부분에서 하나의 함수를 만들어 각 이벤트에 동시에 적용하고 함수 내부에서 구분하여 각 역할에 맞도록 구현하는 것이 저는 개인적으로 무분별하게 함수를 늘리는 것보다 반복을 줄일 수 있어서 좋은 것 같습니다.
잘하셨어요.
하지만, Todo 컴포넌트에서 todoState의 조건에 따라 리턴문이 다르고 리턴문 안에서도 isDone의 상태에 따라 또 코드가 나뉘는데 물론 이런 방식으로 구현할 수 있겠지만 제가 보기에는 오히려 이런 부분이 조금 더 복잡하게 느껴지는 것 같아요.
또한 코드도 사실 '완료'와 '취소' 문구만 다르고 대부분 형태가 동일하기 때문에 오히려 리턴문은 하나만 두고 변경이 되어야 하는 부분만 조건에 따라 다르게 보여줄 수 있으면 좋을 것 같습니다.

4. **DOM의 직접 접근 최소화**
React에는 가상돔이라는 개념이 존재하며 실제 DOM에 접근하는 코드는 최소화하는 것이 좋습니다.
DOM에 직접 접근한 코드는 무엇이고 이러한 방법이 아닌 가상돔에 접근하여 코드를 짤 수 있는 방법을 학습해 보시면 좋을 것 같습니다.

5. **State의 관리**
cnt를 State로 관리하는 이유는 useEffect에서 의존성 배열에 두고 리렌더링하기 위함인가요?
return문 내부에서는 사용이 되지 않고 혹시나 중복되는 state가 있지는 않은지 살펴보면 좋을 것 같습니다.
현재는 add 버튼을 눌렀을 때 cnt라는 State가 업데이트되고 이 cnt는 useEffect의 의존성 배열이기 때문에 useEffect 내부에서 todos라는 State를 또 업데이트 하고 있는 형식이라 State만으로도 관리할 수 있는 부분을 useEffect를 통해 리렌더링되는 문제가 있을 것 같습니다.
또한, todos의 경우 State로 관리하고 있으나 해당 부분을 업데이트 할 때에 useState의 setter함수가 아닌 push를 통해 변경해주고 있는데 과연 이는 state를 올바르게 사용하고 있는걸까? 고민해 보시면 좋을 것 같아요.
추가로 title, body의 경우 todo 아이템 하나의 제목과 내용이 맞을까요?
해당 부분은 결국 todo 아이템을 형성하는 하나로 묶인 존재이고 이는 각각의 state를 만들어 따로 관리하는 것 보다 하나의 state에서 두개의 input값을 관리하는 것이 state도 줄이고 코드도 줄일 수 있는 방법일 것 같습니다.

고생많으셨습니다:)

**Comment by godjooyoung** [comment]
답변 감사합니다! 코드 전체보고리뷰해주셔서 너무 감사합니다. 말씀주신것들 반영해서 리팩토링 해보겠습니다!!!!!

**Comment by godjooyoung** [comment]
안녕하세요. 기술매니저님. 항해 14기 신주영입니다.
코맨트랑 면담때 해주신 말씀 바탕대로 코드 수정 하였습니다.

- 리드미를 조금 더 상세하게 작성해 보았습니다. 코드를 작성하면서 있었던 이슈 부분들도 레벨2 과제하면서 추가해보도록 하겠습니다.

- 불필요한 파일 : 로고이미지, reportWebVitals.js 삭제 (성능 측정 CRA 자동생성 파일), mainfast.json (유저 디바이스에 제공되는 메타정보 파일) 등 기본적으로 생성되지만 현재 프로젝트에서 사용되지 않는 파일들을 삭제했습니다. Index.html에서 불필요한 기본 주석이랑 import도 삭제하였습니다. 혹시 제가 더 삭제해야할 파일들이 잇을가요? 아니면 삭제하면 안되는 파일인데 삭제한 것들이 있을까요?

- 동일코드 반복 최소화  : 기존의 Todo 컴포넌트에서 todoState의 조건에 따라 리턴문이 다른 경우는 말씀하신대로 줄일수 있을것 같아서 하나의 리턴문 안에서 삼항식으로 버튼의 명칭만 바꿔주는 형태로 변경하였습니다.

- DOM의 직접 접근 최소화 : 직접적으로 돔에 접근하고 있는 document.getElement~~ 구문을 삭제하고 이미 state로 관리하고 있었던 값이기 때문에 스테이트의 값을 읽어오는 형태로 변경하였습니다.

- State의 관리 : 기존에 객체안의 값들을 하나하나 state로 관리하던 부분을 변경하고 todo state와 todos state를 사용하였습니다.
id는 유니크한 값만 생성되면 된다고 하셔서 useEffect 훅 사용하던 부분을 제거하고 펑션 외부에서 전역으로 선언하여서 카운트를 증가해주는 방식으로 변경하였습니다.

- App.jsx의 용법 : 면담때 App.jsx의 역할을 생각해보는게 좋을것 같다고 말씀해주신걸 제가 제대로 이해한게 맞을까요? App.jsx는 단순히 컴포넌트를 불러와서 리턴만 해주는 형태로 구현했습니다. 기존의 App.jsx에서 수행하던 로직을 컴포넌트를 분리해서 TodoList.jsx에서 Todo.jsx를 받아서 구현하는 형태로 변경하였습니다.

소스코드 전체를 보고 리뷰 해주시는게 번거로우셨을텐데 꼼꼼히 봐주셔서 이전보다는 간결한 소스코드가 된 것 같습니다.
감사합니다.
