### ISSUE TITLE
[요청] 리덕스,리듀스 사용관련 코드리뷰 부탁드립니다.

### ISSUE THREAD

**Issue by godjooyoung** [godjooyoung/first-react-to-do#3]
안녕하세요 김나영 기술매니저님.
항해 14기 신주영입니다.
리덕스랑 라우터를 사용해서 기존의 TODO를 리팩토링 하는 과정을 거쳤습니다.

리덕스를 처음 사용해보는 거라서 잘 사용한 것인지 궁금해서 리뷰 요청드립니다.

### src/redux/modules/todoReduser.js
투두리듀서를 두고 그 안에 초기 상태값을 투두의 상세내용을 담는 todo라는 키를 가진 객체와,
투두의 목록을 담는 빈 배열을 todoList 란 키를 가진 배열을 두었습니다. 

이렇게 객체로 초기값을 지정해주니까 투두랑 투투리스트를 모두 하나의 스테이트로 관리할 수있을것 같아서 이렇게 구현했습니다,
(리듀서를 두개 만들거나 초기상택값을 두개 만들고 싶지 않아서 이렇게 구현해보았습니다.)

문제는 전역 스테이트에 접근할때 매번 .으로 안으로 안으로 들어가서 해야해서 번거로운것 같기도 합니다.

보통은 어떻게 사용하시는지 궁금합니다.
```jsx
// 초기상태값
const initState = {
    todo : {
        id: 0,
        isDone: false,
        title:'',
        body:''
    },
    todoList : []
}
```

### src/redux/modules/todoReduser.js
리듀서에서 이런식으로 액션크리에이터를 만들고 화면에서 넘겨주는 값을
페이로드로 받아서 리듀서를  통해 액션을 구분한 다음 해당 스위치문에서 리턴할때 데이터를 가공해주는형태로 사용했습니다.

```jsx
// ActionCreater
 export const deleteTodo = (data) => {
    return {
        type: DELETE_TODO,
        payload : data,
    }
}

/** 중략 */

/**
 * 리듀서 : state를 액션의 타입에 맞추어서 변화를 일으키는 함수
 * 액션 : state를 어떻게 변화시킬지 타입과 내용을 기록한것
 * @param {} initState 
 * @param {} action 
 */


const todoReducer = (state = initState, action) => {
    console.log("0. state:",state, ", state.id:",state.id)
    switch (action.type) {
        case CRATE_TODO:
            return {
                todo : {
                    id: state.todo.id + 1,
                    isDone: false,
                    title: '',
                    body: ''
                },
                todoList : [...state.todoList, state.todo]
            }
        case DELETE_TODO:       
            state.todoList = state.todoList.filter((x)=>{
                return x.id != action.payload
            })
            return {
                todo : {
                    id: state.todo.id,
                    isDone: false,
                    title: '',
                    body: ''
                },
                todoList : state.todoList
            }
        case UPDATE_TODO:
            return {
                todo : {
                    id: state.todo.id,
                    title: action.payload.title,
                    body: action.payload.body,
                    isDone : false
                },
                todoList : state.todoList
            }
        case TOGGLE_TODO:
            state.todoList.map((x) => {
                    if(x.id == action.payload){
                        x.isDone = !x.isDone
                    }
                }
            );
            return {
                todo : {
                    id: state.todo.id,
                    isDone: false,
                    title: '',
                    body: ''
                },
                todoList : [...state.todoList]
            }
        case SELECT_TODO:
            // TODO 상세보기, 상세보기 하면서 상태값 변경 (리스트는 그대로 입력값은 초기값으로
            return {
                todo : {
                    id: state.todo.id,
                    isDone: false,
                    title: '',
                    body: ''
                },
                todoList : state.todoList
            }

        default:
            return {
                todo : {
                    id: state.todo.id,
                    isDone: false,
                    title: '',
                    body: ''
                },
                todoList : []
            }    
    }
}
```

간단한 서비스지만 이렇게 복잡해지기도 했고.. 또 서비스가 커질수록 리듀서 내의 스위치 문에서 로직이 길어지기도 할텐데 이렇게 리듀서 내에서 데이터를 가공해서 리턴해준는게 맞는 형태일까요? 궁금합니다..

아, 저번 리뷰해주신 내용은 반영해서 적용해보았습니다!
바쁘실텐데 코드리뷰 해주셔서 감사합니다.

@
(p.s. 이렇게 이슈를 달면 되는걸까요? 혹시 멘션을 걸어야 하는걸까요? 멘션 하려다가.. 나영기술매니저님 깃에 이상한게 남게 될까바 따로 하지 않았습니다!)

**Comment by skdud4659** [comment]
안녕하세요 주영님:)

이슈 남겨주신 부분 잘 읽어보았습니다. 
주특기 1주차에 진행한 코드에서 추가적으로 리덕스와 라우터를 사용하여 이번 주차 진행하신거죠?!
그럼 level2 진행 사항이라고 생각하고 리뷰 진행하겠습니다.

1. 혹시 지난번 제가 리뷰 때 각각의 state를 만들어 따로 관리하는 것 보다 하나의 state에서 두 개의 Input 값을 관리하는 것에 대해서 얘기했는데 기억하시나요?
이것처럼 상태를 관리한다는 것은 여러개의 상태를 만들어서 관리하기 보다 비슷한 역할의 상태를 묶어서 한번에 관리하는 것이 더 좋습니다.
이를 리덕스에 대입해보면 하나의 리덕스 모듈이 useState 처럼 상태를 관리해주는 역할을 한다고 생각하면 됩니다.
그렇다면 주영님께서 만드신 initState 처럼 하나의 리덕스 모듈에서 todo와 todoList를 묶어서 객체로 관리하고 있는 것이니 저는 매 state마다 모듈을 만드는 것 보다 이렇게 비슷한 역할을 가진 state들끼리 모아서 하나의 모듈에서 관리하는 것이 좋다고 생각하고, 실제로 이렇게 사용하는 편입니다.

2. 리듀서를 작성할 때에는 상태관리가 필요한 액션에 대해서만 작성해 주면 됩니다.
예를 들어서 하나의 아이템에 대해서 삭제 버튼을 누르면 delete API 통신 후 다시 화면이 렌더링 되어 get 요청을 해온다고 생각해 봅시다.
그럼 여기서 어차피 delete 후 get 요청을 다시 해올 것이고 get 요청 액션의 리듀서에서는 initState에 해당 데이터 값을 넣어줄테니 delete 후 마땅히 상태를 처리할 부분이 없다고 가정한다면, 굳이 delete 액션에 대한 리듀서는 작성하지 않아도 괜찮은 것이지요.
(여기에서 추후 redux-toolkit이나 데이터 통신에 실패했을 때의 예외 처리를 해준다고 하면 작성하셔야 해요. 단순 예시입니다.)
액션이 많아질수록 리듀서가 길어지는 것은 당연하고 그렇기 때문에 최대한 비슷한 역할의 state끼리 모듈을 나눠서 관리하기도 합니다.

다음 레벨부터도 작업하시다 어려웠던 부분에 대해서 이렇게 이슈 남겨주시면 좋을 것 같아요!
따로 언급하지 않으셔도 진행 사항을 매니저들이 체크하고 있어서 과제를 제출하시면 들어와서 확인하겠습니다:)

추가로 궁금하신 부분은 댓 달아주시거나 순회 시간에 찾아와주세요!

그럼 오늘도 화이팅-!

**Comment by godjooyoung** [comment]
김나영 기술매니저님!!
늘 꼼꼼히 리뷰해주셔서 감사합니다!
저번에 말씀해주신 상태는 최대한 적게 만드는게 좋다고 하셔서 하나로 합쳐보려고 고민해봤습니다. 감사합니다. ㅎㅎ
